<a href="https://colab.research.google.com/github/NeerajVeerla/CVworkshop/blob/master/Day2/knnScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from sklearn.datasets import load_iris
from numpy.random import randint
import numpy
import matplotlib.pyplot as plt
numpy.random.seed(0)

#loading data
iris=load_iris()

#store feature  matrix in X
X=iris.data
#target in y
y=iris.target

#
train_idx=xxx=randint(0,150,100)
X_train=X[train_idx]
y_train=y[train_idx]

test_idx=numpy.setdiff1d(range(150),train_idx)
X_test=X[test_idx]
y_test=y[test_idx]

print(X_test)






[[4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [4.8 3.1 1.6 0.2]
 [5.5 4.2 1.4 0.2]
 [4.9 3.6 1.4 0.1]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [5.6 3.  4.5 1.5]
 [6.1 2.8 4.  1.3]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [5.5 2.4 3.8 1.1]
 [6.  2.7 5.1 1.6]
 [6.7 3.1 4.7 1.5]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [5.8 2.6 4.  1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.

In [7]:
print(X_train)

[[4.6 3.2 1.4 0.2]
 [7.7 3.8 6.7 2.2]
 [5.8 2.7 4.1 1. ]
 [6.3 2.9 5.6 1.8]
 [4.9 3.1 1.5 0.1]
 [5.1 3.7 1.5 0.4]
 [5.5 3.5 1.3 0.2]
 [6.3 2.3 4.4 1.3]
 [5.9 3.2 4.8 1.8]
 [5.6 3.  4.1 1.3]
 [6.7 3.1 5.6 2.4]
 [6.6 2.9 4.6 1.3]
 [5.1 3.4 1.5 0.2]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.4 3.7 1. ]
 [5.  3.  1.6 0.2]
 [6.7 3.  5.  1.7]
 [6.3 2.5 4.9 1.5]
 [4.9 3.1 1.5 0.1]
 [6.2 3.4 5.4 2.3]
 [6.4 3.2 5.3 2.3]
 [5.7 2.6 3.5 1. ]
 [5.8 2.7 3.9 1.2]
 [5.7 2.8 4.1 1.3]
 [4.7 3.2 1.6 0.2]
 [6.5 3.  5.2 2. ]
 [6.5 3.  5.2 2. ]
 [5.8 2.7 5.1 1.9]
 [5.2 4.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [6.1 3.  4.9 1.8]
 [5.2 4.1 1.5 0.1]
 [5.4 3.4 1.5 0.4]
 [5.8 2.8 5.1 2.4]
 [5.2 3.4 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [6.4 2.8 5.6 2.1]
 [6.4 2.8 5.6 2.1]
 [5.5 2.3 4.  1.3]
 [6.3 2.8 5.1 1.5]
 [4.4 3.  1.3 0.2]
 [5.1 3.5 1.4 0.3]
 [5.7 2.6 3.5 1. ]
 [6.4 2.8 5.6 2.2]
 [7.6 3.  6.6 2.1]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [6.9 3.2 5.7 2.3]
 [4.9 3.  1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [4.9 2.4 3.3 1. ]
 [5.  3.2 1.

In [10]:
X_train.shape

(100, 4)

In [11]:
X_test.shape

(78, 4)

In [12]:

for k in range(78):
  min=9999
  for i in range(100):
    
    dist = numpy.sqrt(numpy.sum(numpy.square((X_test[k] - X_train[i]))))
    if(dist<min):
      min=dist
      label=y_train[i]
  
  y_test[k]=label

print(y_test)




[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 1]


In [19]:
for k in range(78):
  min=9999
  for i in range(100):
    
    dist = numpy.sqrt(numpy.sum(numpy.square((X_test[k] - X_train))))
  print(dist)
  

35.66146379497062
34.62138067726358
34.57773850326247
31.9631037291437
33.64015457752833
36.028322192408574
33.386823748299264
34.966269460724575
38.68074456367147
35.93688912524288
34.68861484694943
34.66006347368683
31.764130713746912
33.78401989106684
31.603480820947556
38.44918724758691
31.678068122914315
32.41141774128371
33.349062955351535
33.33466664000107
35.26953359487477
35.12833614050059
34.841067721870985
36.7894006474691
30.984835000367518
34.371499821800036
33.42244754652179
26.259093662957984
23.458900229976685
26.66120777459266
24.156986567036874
22.60088493842664
24.15864234595976
22.326665671344657
25.10019920239678
21.81375712709757
23.12704045052025
23.50148931450941
21.327447104611466
22.679506167463174
21.664717861075413
23.527430798963156
22.74510936443261
23.62837277511932
25.866194153759846
22.336517185989404
25.692800548013444
25.06351930595542
22.177916944564473
22.755658636919303
21.75362038833996
21.692855966884583
22.29035665932692
26.20648774635777
31.831